fix(location): Increased the throttling duration to 2 seconds for location updates (#97)
Since we are still getting a good amount of sentry error like the
following:

> PlatformLocalizedException: The endpoint has been modified
concurrently, and it has an exclusive lock. Please try again later

We have moved the maximum of location update request to one every 2
seconds.